### ISSUE TITLE
Response content cannot be parsed... UseBasicParsing paramater

### ISSUE THREAD

**Issue by nsreenanhks** [Sayannara/Check-SPOBrokenLink#1]
Hi Yann, not sure if this would be considered an issue or not, but I was receiving the following:

"This is site page
Dead Link
The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again."

I modified Test-URL.ps1 from
$SiteStatus = Invoke-WebRequest $URL

to

$SiteStatus = Invoke-WebRequest -Uri $URL -UseBasicParsing

per

https://stackoverflow.com/questions/38005341/the-response-content-cannot-be-parsed-because-the-internet-explorer-engine-is-no

and this seemed to fix it

**Comment by Sayannara** [comment]
Hi nsreenanhks,

Firstly, thanks for your message. Secondly, I'm really sorry as I see it only today :-/ Hopefully, your message didn't expect an answer. 'm not sure now, it may be necessary if you use invoke-webRequest from windows client or server. As I'm not able to do further tests, I added a comment to the function with your suggestion.

Yann

**Comment by Sayannara** [comment]
Added a comment in the function with the suggestion.

**Comment by nsreenanhks** [comment]
Hi Yann! No worries at all, thank you for following up here, understood!
